# Generated by Django 3.2.5 on 2021-08-06 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor', '0002_vendor_slug'),
        ('shop', '0004_auto_20210806_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='vendors',
            field=models.ManyToManyField(related_name='orders', to='vendor.Vendor'),
        ),
    ]
